import logging

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)

logging.getLogger("prawcore").setLevel(logging.ERROR)
logging.getLogger("urllib3").setLevel(logging.ERROR)

MAX_NUMBERS = {
    "max_age": 7 * 24 * 60 * 60,
    "max_score": 100,
    "max_comments": 2000,
    "max_view_count": 10000
}

SCORE_WEIGHTS = {
    "base": 1000,
    "age": 1,
    "score": 0.5,
    "num_comments": 0.3,
    "view_count": 0.2
}

REDDIT_CLIENT_ID = "NL5_XWbiscQr6ZQSf7zAOw"
REDDIT_CLIENT_SECRET = "4JExOQAJ5ZQl8pENW5Dphs-udeI6Xg"

GENERAL_CRYPTO_KEYWORDS = ["cryptocurrency", "blockchain", "decentralization", "distributed ledger", "smart contracts",
                           "DeFi", "Decentralized Finance", "NFT", "Non-Fungible Token", "tokenomics", "crypto mining",
                           "staking", "proof of work", "PoW", "proof of stake", "PoS", "hashrate", "consensus mechanism",
                           "hard fork", "soft fork", "private key", "public key", "crypto wallet", "cold wallet",
                           "hot wallet", "DEX", "Decentralized Exchange", "CEX", "Centralized Exchange", "liquidity pool",
                           "gas fees", "layer 1 blockchain", "layer 2 scaling", "smart contract auditing",
                           "blockchain oracle", "governance token", "stablecoin", "yield farming", "impermanent loss",
                           "token swap", "dApp", "Decentralized Application", "Decentralized Autonomous Organization",
                           "DAO", "airdrop", "rug pull", "whitelist", "Initial Coin Offering", "Initial DEX Offering",
                           "ICO", "IDO", "Initial Exchange Offering", "IEO", "crypto whale", "HODL", "staking rewards",
                           "zk-SNARKs", "Zero-Knowledge Succinct Non-Interactive Argument of Knowledge", "zk-rollups",
                           "sidechains", "cross-chain interoperability", "wrapped token", "governance protocol",
                           "flash loan", "MEV", "Miner Extractable Value", "on-chain analysis", "off-chain transactions",
                           "liquidity mining", "crypto regulations", "privacy coins", "multi-signature", "fungibility",
                           "synthetic assets", "crypto bridge", "hashgraph", "altcoin",
                           "Ethereum Virtual Machine", "EVM", "gas limit", "staking pool", "TVL", "Total Value Locked",
                           "crypto network congestion", "zero-knowledge proof", "blockchain scalability",
                           "decentralized storage", "digital identity", "token burn", "rebase token", "stable swap",
                           "flashbots", "rollups", "metaverse economy", "fractionalized NFT", "crypto custody",
                           "security token", "social tokens", "CBDC", "Central Bank Digital Currency"]

CRYPTO_MAP = {
    "1INCH": "1inch",
    "AAVE": "Aave",
    "ACH": "Alchemy Pay",
    "ADA": "Cardano",
    "ADX": "AdEx",
    "ALGO": "Algorand",
    "ALICE": "MyNeighborAlice",
    "ALPINE": "Alpine F1 Team Fan Token",
    "AMP": "Amp",
    "ANKR": "Ankr",
    "ANT": "Aragon",
    "APE": "ApeCoin",
    "API3": "API3",
    "APT": "Aptos",
    "ARB": "Arbitrum",
    "ASTR": "Astar",
    "ATOM": "Cosmos",
    "AUDIO": "Audius",
    "AVAX": "Avalanche",
    "AXL": "Axelar",
    "AXS": "Axie Infinity",
    "BAL": "Balancer",
    "BAND": "Band Protocol",
    "BAT": "Basic Attention Token",
    "BCH": "Bitcoin Cash",
    "BICO": "Biconomy",
    "BLUR": "Blur",
    "BNB": "Binance Coin",
    "BNT": "Bancor",
    "BOND": "BarnBridge",
    "BONK": "Bonk",
    "BOSON": "Boson Protocol",
    "BTC": "Bitcoin",
    "BTRST": "Braintrust",
    "BUSD": "Binance USD",
    "CELO": "Celo",
    "CELR": "Celer Network",
    "CHZ": "Chiliz",
    "CLV": "Clover Finance",
    "COMP": "Compound",
    "COTI": "COTI",
    "CRV": "Curve DAO Token",
    "CTSI": "Cartesi",
    "CUDOS": "Cudos",
    "DAI": "Dai",
    "DAR": "Mines of Dalarnia",
    "DASH": "Dash",
    "DGB": "DigiByte",
    "DIA": "DIA",
    "DOGE": "Dogecoin",
    "DOT": "Polkadot",
    "EGLD": "Elrond",
    "ENJ": "Enjin Coin",
    "ENS": "Ethereum Name Service",
    "EOS": "EOS",
    "ETC": "Ethereum Classic",
    "ETH": "Ethereum",
    "FET": "Fetch.ai",
    "FIL": "Filecoin",
    "FLOKI": "Floki Inu",
    "FLOKI8": "Floki Inu (ERC-20)",
    "FLOW": "Flow",
    "FLUX": "Flux",
    "FORT": "Forta",
    "FORTH": "Ampleforth Governance Token",
    "FTM": "Fantom",
    "G": "Gnosis",
    "GAL": "Galatasaray Fan Token",
    "GALA": "Gala",
    "GLM": "Golem",
    "GRT": "The Graph",
    "GTC": "Gitcoin",
    "HBAR": "Hedera",
    "HNT": "Helium",
    "ICP": "Internet Computer",
    "ICX": "ICON",
    "ILV": "Illuvium",
    "IMX": "Immutable X",
    "IOST": "IOST",
    "IOTA": "IOTA",
    "IOTX": "IoTeX",
    "JAM": "Geojam Token",
    "JASMY": "JasmyCoin",
    "KAVA": "Kava",
    "KDA": "Kadena",
    "KNC": "Kyber Network Crystal",
    "KSHIB": "Kilo Shiba Inu",
    "KSM": "Kusama",
    "LAZIO": "Lazio Fan Token",
    "LDO": "Lido DAO Token",
    "LINK": "Chainlink",
    "LOKA": "League of Kingdoms Arena",
    "LOOM": "Loom Network",
    "LPT": "Livepeer",
    "LRC": "Loopring",
    "LSK": "Lisk",
    "LTC": "Litecoin",
    "LTO": "LTO Network",
    "MAGIC": "Magic",
    "MANA": "Decentraland",
    "MASK": "Mask Network",
    "MATIC": "Polygon",
    "MKR": "Maker",
    "MXC": "MXC",
    "NANO": "Nano",
    "NEAR": "NEAR Protocol",
    "NEO": "Neo",
    "NMR": "Numeraire",
    "OCEAN": "Ocean Protocol",
    "OGN": "Origin Protocol",
    "OMG": "OMG Network",
    "ONE": "Harmony",
    "ONG": "Ontology Gas",
    "ONT": "Ontology",
    "OP": "Optimism",
    "ORBS": "Orbs",
    "OXT": "Orchid",
    "PAXG": "PAX Gold",
    "PENGU": "PenguCoin",
    "PEPE": "PepeCoin",
    "PNUT": "Peanut",
    "POL": "Proof of Liquidity",
    "POLY": "Polymath",
    "POLYX": "Polymesh",
    "POND": "Marlin",
    "PORTO": "FC Porto Fan Token",
    "PROM": "Prometeus",
    "QNT": "Quant",
    "QTUM": "Qtum",
    "RAD": "Radicle",
    "RARE": "SuperRare",
    "REEF": "Reef",
    "REN": "Ren",
    "RENDER": "Render Token",
    "REP": "Augur",
    "REQ": "Request",
    "RLC": "iExec RLC",
    "RNDR": "Render Token",
    "ROSE": "Oasis Network",
    "RVN": "Ravencoin",
    "SAND": "The Sandbox",
    "SANTOS": "Santos FC Fan Token",
    "SHIB": "Shiba Inu",
    "SKL": "SKALE Network",
    "SLP": "Smooth Love Potion",
    "SNX": "Synthetix",
    "SOL": "Solana",
    "SPELL": "Spell Token",
    "SRM": "Serum",
    "STG": "Stargate Finance",
    "STMX": "StormX",
    "STORJ": "Storj",
    "SUI": "Sui",
    "SUSHI": "SushiSwap",
    "SYS": "Syscoin",
    "T": "Threshold",
    "TFUEL": "Theta Fuel",
    "THETA": "Theta Network",
    "TLM": "Alien Worlds",
    "TRAC": "OriginTrail",
    "TRUMP": "TrumpCoin",
    "TRX": "TRON",
    "TUSD": "TrueUSD",
    "UNI": "Uniswap",
    "USD": "USD Coin",
    "USD4": "USD4",
    "USDC": "USD Coin",
    "USDT": "Tether",
    "UST": "TerraUSD",
    "VET": "VeChain",
    "VITE": "Vite",
    "VOXEL": "Voxies",
    "VTHO": "VeThor Token",
    "WAVES": "Waves",
    "WAXP": "WAX",
    "WBTC": "Wrapped Bitcoin",
    "WIF": "Dogwifhat",
    "XEC": "eCash",
    "XLM": "Stellar",
    "XNO": "XNO",
    "XRP": "XRP",
    "XTZ": "Tezos",
    "YFI": "Yearn.finance",
    "ZEC": "Zcash",
    "ZEN": "Horizen",
    "ZIL": "Zilliqa",
    "ZRX": "0x"
}
