import logging
import warnings

warnings.filterwarnings("ignore")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)

logging.getLogger("prawcore").setLevel(logging.ERROR)
logging.getLogger("urllib3").setLevel(logging.ERROR)

MAX_NUMBERS = {
    "max_age": 7 * 24 * 60 * 60,
    "max_score": 100,
    "max_comments": 2000,
    "max_view_count": 10000
}

SCORE_WEIGHTS = {
    "base": 1000,
    "age": 1,
    "score": 0.5,
    "num_comments": 0.3,
    "view_count": 0.2
}

REDDIT_CLIENT_ID = "NL5_XWbiscQr6ZQSf7zAOw"
REDDIT_CLIENT_SECRET = "4JExOQAJ5ZQl8pENW5Dphs-udeI6Xg"

GENERAL_CRYPTO_KEYWORDS = ["cryptocurrency", "blockchain", "decentralization", "distributed ledger", "smart contracts",
                           "DeFi", "Decentralized Finance", "NFT", "Non-Fungible Token", "tokenomics", "crypto mining",
                           "staking", "proof of work", "PoW", "proof of stake", "PoS", "hashrate", "consensus mechanism",
                           "hard fork", "soft fork", "private key", "public key", "crypto wallet", "cold wallet",
                           "hot wallet", "DEX", "Decentralized Exchange", "CEX", "Centralized Exchange", "liquidity pool",
                           "gas fees", "layer 1 blockchain", "layer 2 scaling", "smart contract auditing",
                           "blockchain oracle", "governance token", "stablecoin", "yield farming", "impermanent loss",
                           "token swap", "dApp", "Decentralized Application", "Decentralized Autonomous Organization",
                           "DAO", "airdrop", "rug pull", "whitelist", "Initial Coin Offering", "Initial DEX Offering",
                           "ICO", "IDO", "Initial Exchange Offering", "IEO", "crypto whale", "HODL", "staking rewards",
                           "zk-SNARKs", "Zero-Knowledge Succinct Non-Interactive Argument of Knowledge", "zk-rollups",
                           "sidechains", "cross-chain interoperability", "wrapped token", "governance protocol",
                           "flash loan", "MEV", "Miner Extractable Value", "on-chain analysis", "off-chain transactions",
                           "liquidity mining", "crypto regulations", "privacy coins", "multi-signature", "fungibility",
                           "synthetic assets", "crypto bridge", "hashgraph", "altcoin",
                           "Ethereum Virtual Machine", "EVM", "gas limit", "staking pool", "TVL", "Total Value Locked",
                           "crypto network congestion", "zero-knowledge proof", "blockchain scalability",
                           "decentralized storage", "digital identity", "token burn", "rebase token", "stable swap",
                           "flashbots", "rollups", "metaverse economy", "fractionalized NFT", "crypto custody",
                           "security token", "social tokens", "CBDC", "Central Bank Digital Currency"]

CRYPTO_MAP = {
    "1INCH": "1inch",
    "AAVE": "Aave",
    "ADA": "Cardano",
    "AIOZ": "AIOZ Network",
    "ALG": "Algorand",
    "ALGO": "Algorand",
    "ALT11M2507": "ALT11M2507",
    "ALT11M250830": "ALT11M250830",
    "ALT11M251029": "ALT11M251029",
    "ALT2612": "ALT2612",
    "AMPL": "Ampleforth",
    "APE": "ApeCoin",
    "APENFT": "APENFT",
    "APT": "Aptos",
    "ARB": "Arbitrum",
    "ATH": "Atheneum",
    "ATO": "Cosmos",
    "ATOM": "Cosmos",
    "AUSDT": "Aave USDT",
    "AUSTRALIA200IX": "Australia 200 Index",
    "AVAX": "Avalanche",
    "AXS": "Axie Infinity",
    "AZERO": "Aleph Zero",
    "B2M": "Bit2Me",
    "BCH": "Bitcoin Cash",
    "BEST": "Bitpanda Ecosystem Token",
    "BGB": "Bitget Token",
    "BLAST": "SafeBlast",
    "BNB": "Binance Coin",
    "BONK": "Bonk",
    "BTC": "Bitcoin",
    "BTCDOM": "Bitcoin Dominance",
    "BTT": "BitTorrent",
    "BVIV": "BVIV",
    "BXN": "Bixen Token",
    "CCD": "Concordium",
    "CELO": "Celo",
    "CHEX": "CHEX Token",
    "CHZ": "Chiliz",
    "CNHT": "Tether CNH",
    "COMP": "Compound",
    "CRV": "Curve DAO Token",
    "DAI": "Dai",
    "DASH": "Dash",
    "DOGE": "Dogecoin",
    "DOP": "Dopple Finance",
    "DOT": "Polkadot",
    "DYM": "Dymmax",
    "EGLD": "Elrond",
    "EIGEN": "Eigen",
    "ENA": "Enapter",
    "EOS": "EOS",
    "ETC": "Ethereum Classic",
    "ETH": "Ethereum",
    "ETH2X": "Ethereum 2x Flexible Leverage Index",
    "ETHW": "EthereumPoW",
    "EUROPE50IX": "Europe 50 Index",
    "EURQ": "EURQ",
    "EURR": "EURR",
    "EURT": "Tether EUR",
    "EVIV": "EVIV",
    "FET": "Fetch.ai",
    "FIL": "Filecoin",
    "FLOKI": "Floki Inu",
    "FRANCE40IX": "France 40 Index",
    "FTM": "Fantom",
    "GALA": "Gala",
    "GMMT": "GMMT",
    "GOMINING": "GoMining Token",
    "GRT": "The Graph",
    "GTX": "GTX",
    "HILSV": "HILSV",
    "HIX": "HIX",
    "HMSTR": "Hamster",
    "HONGKONG50IX": "Hong Kong 50 Index",
    "HTXDAO": "HTXDAO",
    "ICP": "Internet Computer",
    "IOT": "IOTA",
    "IOTA": "IOTA",
    "JAPAN225IX": "Japan 225 Index",
    "JASMY": "JasmyCoin",
    "JST": "JUST",
    "JUP": "Jupiter",
    "JUSTICE": "JUSTICE",
    "JXX": "JXX",
    "KAN": "BitKan",
    "KARATE": "Karate Combat",
    "KAVA": "Kava",
    "KMNO": "KMNO",
    "LDO": "Lido DAO",
    "LEO": "UNUS SED LEO",
    "LIFIII": "LIFIII",
    "LINK": "Chainlink",
    "LTC": "Litecoin",
    "MANA": "Decentraland",
    "MANEKI": "Maneki",
    "MATIC": "Polygon",
    "MEW": "MEW",
    "MIM": "Magic Internet Money",
    "MKR": "Maker",
    "MLN": "Enzyme",
    "MPC": "MPC",
    "MXNT": "Tether MXN",
    "NEAR": "NEAR Protocol",
    "NEO": "NEO",
    "NEXO": "Nexo",
    "NOT": "NOT",
    "NYM": "NYM",
    "OMG": "OMG Network",
    "OMN": "OMN",
    "OPX": "OPX",
    "PEPE": "Pepe",
    "PNK": "Kleros",
    "POL": "Proof of Liquidity",
    "RRT": "Recovery Right Token",
    "SAND": "The Sandbox",
    "SCROLL": "Scroll",
    "SEI": "Sei",
    "SHIB": "Shiba Inu",
    "SOL": "Solana",
    "SPAIN35IX": "Spain 35 Index",
    "SPEC": "SPEC",
    "SPELL": "Spell Token",
    "STG": "Stargate Finance",
    "STRK": "Strike",
    "SUI": "Sui",
    "SUN": "SUN",
    "SUSHI": "SushiSwap",
    "SWEAT": "Sweatcoin",
    "TESTADA": "Test ADA",
    "TESTALGO": "Test Algorand",
    "TESTAPT": "Test Aptos",
    "TESTAVAX": "Test Avalanche",
    "TESTBTC": "Test Bitcoin",
    "TESTDOGE": "Test Dogecoin",
    "TESTDOT": "Test Polkadot",
    "TESTEOS": "Test EOS",
    "TESTETH": "Test Ethereum",
    "TESTFIL": "Test Filecoin",
    "TESTLTC": "Test Litecoin",
    "TESTMATIC": "Test Polygon",
    "TESTNEAR": "Test NEAR Protocol",
    "TESTSOL": "Test Solana",
    "TESTXAUT": "Test Tether Gold",
    "TESTXTZ": "Test Tezos",
    "TIA": "TIA",
    "TITAN1": "Titan Coin",
    "TITAN2": "Titan Coin",
    "TOKEN": "Token",
    "TOMI": "TOMI",
    "TON": "Toncoin",
    "TRX": "TRON",
    "TURBO": "Turbo",
    "TUSD": "TrueUSD",
    "UKOIL": "Crude Oil",
    "UNI": "Uniswap",
    "UOS": "Uphold",
    "USDC": "USD Coin",
    "USDQ": "USDQ",
    "USDR": "USDR",
    "USDT": "Tether",
    "USTBL": "USTBL",
    "UXLINK": "UXLINK",
    "VELAR": "Velar",
    "WBT": "WBT",
    "WHBT": "WHBT",
    "WIF": "WIF",
    "WILD": "WILD",
    "WOO": "WOO Network",
    "XDC": "XDC Network",
    "XLM": "Stellar",
    "XMR": "Monero",
    "XRD": "Radix",
    "XRP": "XRP",
    "XTP": "XTP",
    "XTZ": "Tezos",
    "YFI": "yearn.finance",
    "ZEC": "Zcash",
    "ZKX": "zkSync",
    "ZRO": "Zero",
    "ZRX": "0x"
}
